name: STL containers homework

on: [push, pull_request]

jobs:
  grayscale-image:
    runs-on: ubuntu-latest
    env:
<<<<<<< HEAD
      path: homework/grayscale-image/build
=======
      path: homework/grayscale-images/build
>>>>>>> e4445d3 (grayscale image ready)
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ctest -V
<<<<<<< HEAD

  formatting_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check
      uses: coders-school/github-actions/clang-format-check@main
      with:
        check_path: 'homework/grayscale-img'
=======
>>>>>>> e4445d3 (grayscale image ready)
